const PACKAGE_LEVEL = {
  TRIAL: 'TRIAL',
  BASIC: 'BASIC',
  ADV: 'ADVANCE',
  PRO: 'PRO',
};

const PACKAGE_TYPE = {
  STUDIO: 'STUDIO',
  API: 'API',
  ARTICLE: 'ARTICLE',
  CHARACTER: 'CHARACTER',
};

const PACKAGE_DURATION = {
  MONTH: 'MONTH',
  YEAR: 'YEAR',
};

export { PACKAGE_DURATION, PACKAGE_LEVEL, PACKAGE_TYPE };
